In [1]:
print("Hello","Hello")

Hello Hello


In [4]:
print('''line1
line2
line3''')

line1
line2
line3


In [5]:
8//5

1

In [6]:
9/5


1.8

In [7]:
a = 9/5

In [8]:
type(a)

float

In [14]:
a = 10
b = 10
print(a==b)
print(a>b)
print(a<b)
print(a!=b)
print(a>=b)
print(a<=b)

True
False
False
False
True
True


In [11]:
type(True)

bool

In [18]:
tv_brand = "Samsung"
tv_price = 1000000
string1 = "Tv = %s, Price= %d"%(tv_brand,tv_price)
print(string1)

Tv = Samsung, Price= 1000000


In [7]:
Name = "Aujasvi"
Age = 26
Place = "kurukshetra"
print("%s is of age %d and lives in %s"%(Name,Age,Place))

Aujasvi is of age 26 and lives in kurukshetra


In [21]:
a = "Aujasvi"
string1= "name = %.2s"%(a)
print(string1)

name = Au


In [8]:
string1 = "Hello World"
string1[0:11:2]

'HloWrd'

In [26]:
string1 = "Hello world"
string1[-1:-10:-1]

'dlrow oll'

In [16]:
a = 100
print("%x"%(a))

64


In [32]:
a = 10
print(oct(a))

0o12


In [35]:
a = 10
print("%o"%(a))

12


In [37]:
a = "Hello world" 
print(a[::-1])

dlrow olleH


In [39]:
string1 = "SAMSUNG PRICE = 100000"

In [41]:
print("offset =",string1.find("SAMSUNG"))

offset = 0


In [18]:
List1 = ['Ram',10,90.2,True]

In [19]:
List1[0]='Hi'

In [20]:
List1

['Hi', 10, 90.2, True]

In [21]:
List1[0:3]

['Hi', 10, 90.2]

In [22]:
List1[1:3]

[10, 90.2]

In [49]:
List1[1]

10

In [23]:
string1 = "Hello"

In [52]:
string1[2:3]

'l'

In [24]:
List1 = [1,2,3]


In [25]:
List2 = [4,5,6]

In [64]:
List1.extend(List2)

In [65]:
List1

[1, 2, 3, 4, 5, 6]

In [26]:
List1.append(List2)

In [67]:
List1

[1, 2, 3, 4, 5, 6, [4, 5, 6]]

In [27]:
String1 = "Hello"

In [28]:
List1 = list(String1)

In [29]:
List1

['H', 'e', 'l', 'l', 'o']

In [71]:
String1 = "Ajay Vinay Anil"

In [30]:
List1 = String1.split(" ")

In [73]:
List1

['Ajay', 'Vinay', 'Anil']

In [74]:
List1 = [1,2,3,[4,5,6]]

In [75]:
List1[3][0]

4

In [32]:
List1 = [10,100,3,5,15]

In [33]:
print(List1.count(100))

1


In [89]:
List1 = [10,100,3,5,15]

In [90]:
List2 = List1.copy()

In [91]:
List1[0]="Hello"

In [92]:
print(List1)

['Hello', 100, 3, 5, 15]


In [93]:
print(List2)

[10, 100, 3, 5, 15]


In [94]:
tup1 = (10)

In [95]:
type(tup1)

int

In [34]:
tup1 = ("string")

In [35]:
tup1(type)

TypeError: 'str' object is not callable

In [98]:
type(tup1)

str

In [99]:
tup1 = (10,)

In [100]:
type(tup1)

tuple

In [101]:
list1 = [1]

In [102]:
type(list1)

list

In [103]:
a = 12345

In [104]:
print("%10d"%a)

     12345


In [36]:
string1 = "Chennai"

In [37]:
string1.count(n)

NameError: name 'n' is not defined

In [108]:
string1.count('n')

2

In [109]:
string1.center(30)

'           Chennai            '

In [110]:
String1 = 'the hindu'

In [112]:
title = String1.title()

In [115]:
Capital = String1.title()

In [116]:
Capital.center(30)

'          The Hindu           '

In [117]:
tup1 = (1,2,3,4)

In [128]:
list1 = list(tup1)

In [130]:
list1[0] = 100

In [131]:
list1

[100, 2, 3, 4]

In [133]:
tup1 = tuple(list1)

In [134]:
tup1

(100, 2, 3, 4)

In [38]:
dict1 = {"Name":"Dvaid"}

In [39]:
dict1

{'Name': 'Dvaid'}

In [41]:
dict1 = {"Age":27}

In [42]:
dict1

{'Age': 27}

In [139]:
dict1["Name"]="Ram"

In [140]:
dict1

{'Name': 'Ram'}

In [146]:
i = 5 

if i>10:
    print("yes")
else: 
    print("No")

print("Done")

No
Done


In [148]:
year = 2017

if (year%4)==0:
    print("yes, it's a leap year")
else:
    print("No, it is not a leap year")

No, it is not a leap year


In [43]:
year = 2019

if (year%4)==0:
    print("Yes, It is a leap year")
    
else:
    print("No, It is not a leap year")

No, It is not a leap year


In [151]:
age = 70

if(0<=age <5):
    print("No")
elif (4<age<10):
    print("half")
elif (9<age<60):
    print("full")
else:
    print("senior")

senior


In [45]:
Age = 95

if (0<Age<5):
    print("No")
elif (4<Age<10):
    print("Hlaf")
elif (9<Age<50):
    print("Senior")
else:
    print("Aged")

Aged


In [46]:
marks = int(input("Enter Marks:"))

if (0<=marks<36):
    print("Pass")
elif (35<marks<51):
    print("Second")
elif (50<marks<61):
    print("Second")
else:
    print("First")

Enter Marks:17
Pass


In [1]:
marks = int(input("Enter Marks:"))

if (0<=marks<36):
    print("Pass")
elif (35<marks<51):
    print("Second")
elif (50<marks<61):
    print("Second")
else:
    print("First")

Enter Marks:12
Pass


In [4]:
a = 20
if (a==10):
    print('yes')
else:
    print('No')

No


In [47]:
Dic = {"Name": "XYZ", "Age": 20,"Gender" : "Male","Marks":{"E":25,"M":30,"C":30}}

In [49]:
Dic = {"Name":"Aujasvi","Age":27,"University":"University de Nantes"}
print(Dic)

{'Name': 'Aujasvi', 'Age': 27, 'University': 'University de Nantes'}


In [7]:
Dic["Marks"]["C"]=75

In [8]:
Dic

{'Name': 'XYZ',
 'Age': 20,
 'Gender': 'Male',
 'Marks': {'E': 25, 'M': 30, 'C': 75}}

In [50]:
List1 = [(1,2,"Game",[1,2,3])]

In [54]:
List1 = [1,2,"Game",[1,2,3]]
print(List1)
tup = tuple(List1)
print(tup)

[1, 2, 'Game', [1, 2, 3]]
(1, 2, 'Game', [1, 2, 3])


In [10]:
a = 100

In [14]:
b = a//3

In [15]:
b

33

In [21]:
list1 = [3,4]

In [22]:
list2 = [1,2]


In [23]:
list1.extend(list2)

In [24]:
list1

[3, 4, 1, 2]

In [25]:
List1 = [4,5,6,3]

In [26]:
List2=sorted(List1)

In [27]:
List2

[3, 4, 5, 6]

In [28]:
print("Hello")

Hello


In [29]:
list1 = ['Bagalore','Chennai','Hyderabad','Delhi']

In [30]:
for element in list1:
    print(element)

Bagalore
Chennai
Hyderabad
Delhi


In [9]:
val = int(input("Enter Marks:"))
list1 = [10,20,30,40]
for i in list1:
    if 0<val<5:
        print('small')
    elif 4<val<10:
        print('medium')
    else:
        print('Large')
  

Enter Marks:12
Large
Large
Large
Large


In [10]:
input1 = input()
list1 = input1.split(' ')

12


In [6]:
input1 = input()
list1 = input1.split(' ')

for i in list1:
    if i.isdigit():
        val = int(i)
        if (val<=20):
            print('small')
        elif (20<val<30):
            print('medium')
        else:
            print('Large')
        
    else:
        print("cannot")

-12
cannot


In [2]:
list1 = list(range(5,100,4))

In [3]:
list1

[5,
 9,
 13,
 17,
 21,
 25,
 29,
 33,
 37,
 41,
 45,
 49,
 53,
 57,
 61,
 65,
 69,
 73,
 77,
 81,
 85,
 89,
 93,
 97]

In [15]:
for x in range(1,100,10):
    if (x%2==0):
        print('even')
    else:
        print('odd')

odd
odd
odd
odd
odd
odd
odd
odd
odd
odd


In [8]:
for x in range(1,100,5):
    print(x)

1
6
11
16
21
26
31
36
41
46
51
56
61
66
71
76
81
86
91
96


In [33]:
str1 = "Student"
for x in range(1,100,10):
    temp = str(x)
    str2 = str1 + temp
    print(str2.split())


['Student1']
['Student11']
['Student21']
['Student31']
['Student41']
['Student51']
['Student61']
['Student71']
['Student81']
['Student91']


In [32]:
type(str2)

str

In [39]:
List1 = [1,10,5,'Hello',12]
for i in list1:
    string1 = str(i)
    if not (string1.isdigit()):
        break
    else:
        print(i)
    

In [40]:
a = 0 
while(a<10):
    print(a)
    a+=1


0
1
2
3
4
5
6
7
8
9


In [40]:
a = 0 
while(True):
    print(a)
    a+=1
    if a >10:
        break
        

0
1
2
3
4
5
6
7
8
9
10


# Last two numbers of even and odd of list

In [44]:
count = 0
Listo=[]
Liste = []
myl = [1,2,3,4,5,6,7,8]
for x in myl: 
    if (x%2)!=0:
        Listo.append(x)
    else:
        Liste.append(x)
        
    count=count+1
    if(count==len(myl)):
        break
print(Listo[-2:])
print(Liste[-2:])

[5, 7]
[6, 8]


In [44]:
dict1 = {'Key1':1, 'Key2':2}

for key, val in dict1.items():
    print(key,val)

Key1 1
Key2 2


In [3]:
string1 = "Hello World"

In [4]:
string1

'Hello World'

In [7]:
def isiteven(val):
    if val%2==0:
        return True
    else:
        return False

In [8]:
r = isiteven(10)

In [9]:
r

True

# Function Max

In [28]:
def Maximum(List):
    Max=0
    for item in List:
        if item>Max:
            Max=item
    return Max

List1 = [1,2,3]
r1 = Maximum(List1)
print(r1)

3


In [29]:
def add(val1,val2):
    val3 = val1 + val2
    return val3

In [30]:
r = add(10,20)

r

In [31]:
r 

30

In [48]:
list1 = ["String", 100,200,300]

In [46]:
itr1 = iter(list1)

In [47]:
element = next(itr1)

In [43]:
element

300

In [37]:
element

'String'

In [47]:
list1 = ["String", 100,200,300]

In [50]:
iter1 = iter(list1)

while True:
    element = next(iter1)
    StopIteration
    print(element)

String
100
200
300


StopIteration: 

In [4]:
list1 = ["String", 100,200,300]

In [5]:
ritr = reversed(list1)

In [7]:
next(ritr)

200

# Lamda Function

In [12]:
add1 = lambda x,y: x > y 
r = add1(10,20)
print(r)


False


In [9]:
r = add1(10,20,30)

In [10]:
r

610

In [27]:
list1 = [1,2,3,4]

In [28]:
def double1(a):
    print(a*3)
    return(a*2)

In [29]:
list2 = list(map(double1,list1))
print(list2)

3
6
9
12
[2, 4, 6, 8]


In [41]:
list1 = [1,2,3,4]

In [42]:
def double1(a):
    return(a%2==0)

In [43]:
list2 = list(filter(double1,list1))

In [44]:
list2

[2, 4]

In [45]:
str1 = "TV 10000 WM 20000"

In [46]:
list1 = str1.split(' ')

In [47]:
list1

['TV', '10000', 'WM', '20000']

# Is Digit Func

In [48]:
def numberfunc(alist):
    if alist.isdigit():
        return alist

In [49]:
list2 = list(filter(numberfunc,list1))

In [50]:
list2

['10000', '20000']

In [61]:
list1 
isdigit1 = lambda x : x.isdigit()
list2 = list(filter(isdigit1,list1))

In [62]:
list2

['10000', '20000']

In [63]:
list1 = [1,2,3,4]

In [80]:
def Maximum(x,y):
    
    if x>y:
        print("Largest Number",x)
    else:
        print("Largest Number",y)
from functools import reduce
Max1 = reduce(Maximum, list1)
print(Max1)

Largest Number 2


TypeError: '>' not supported between instances of 'NoneType' and 'int'

In [74]:
val = reduce(Maximum,List1)

NameError: name 'reduce' is not defined

# Iter through list & Print No.

In [85]:
list1 = ["String1","100","String2","200","String3"]


for item in list1:
    if (not(item.isdigit())):
        continue
    print(item)

100
200


In [98]:
x=100
def fun():
    global x
    x = 200
    print(x)

In [99]:
fun()
print(x)

200
200


In [103]:
version = "Python"
def fun_updateversion(val):
    global version 
    version = version + str(val)

fun_updateversion(3.7)
print(version)

Python3.7


In [104]:
version = "Python"
def print_version():
    global version
    print(version)
  

In [105]:
a = {4,1,3,5,7,8,9}

In [106]:
print(a)

{1, 3, 4, 5, 7, 8, 9}


In [51]:
set1 = {1,2,3,4}
set2 = {4,5,6}

result1 = set1 & set2
result2 = set1|set2
result3 = set1-set2
result4 = set2 - set1

print(result1)
print(result2)
print(result3)
print(result4)



{4}
{1, 2, 3, 4, 5, 6}
{1, 2, 3}
{5, 6}


# Numpy Array 

In [119]:
import  numpy as np

In [121]:
myarr = np.array([1,2,3,4])
print(myarr)

[1 2 3 4]


In [122]:
List1 = [1,2]
List2 = [3,4]
List3 = List1 + List2

In [123]:
List3

[1, 2, 3, 4]

In [124]:
List1 = np.array([1,2,3])
List2 = np.array([4,5,6])
List3 = List1 + List2 
print(List3)

[5 7 9]


In [134]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.dot(b,a)
print(c)

[[23 34]
 [31 46]]


In [136]:
import sys
a = 10
sys.getsizeof(a)
list1=[1,2,3,4]
sys.getsizeof(list1[0])*len(list1)

112

In [13]:
import numpy as np
import sys
list1 = list(range(1000))
total = sys.getsizeof(list1[0])*len(list1)
print(total)

arr1 = np.arange(1000)

print(arr1)

arr1.size
arr1.itemsize

24000
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 

4

In [1]:
import numpy as np

In [52]:
tu = (1,2,3)

In [53]:
type(tu)

tuple

In [54]:
a = {1,2,3}

In [55]:
type(a)

set

In [6]:
type(tu)
out_tu = np.array(tu)
print((out_tu))
print(type(out_tu))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
imp = [1,2,3]
out_1 = np.array(imp)
print(out_1)
type(out_1)

[1 2 3]


numpy.ndarray

In [13]:
sq = np.arange(9)
print(sq)
print(sq.ndim)
print(sq.shape)

[0 1 2 3 4 5 6 7 8]
1
(9,)


In [17]:
my_array = np.arange(9)

print(my_array)


print(my_array.size)

print(my_array.itemsize)

print(my_array.nbytes)

[0 1 2 3 4 5 6 7 8]
9
4
36


In [19]:
print(len(my_array))

my_array.astype(str)
my_array.astype(int)
my_array.astype(float)

9


array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [20]:
print(np.arange(9))

print(np.arange(1,11))

print(np.arange(1,12,3))

[0 1 2 3 4 5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]


In [57]:
import numpy as np
np.linspace(1,3,num=6)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [24]:
cvalues = [20.1,20.5,21.9]

C = np.array(cvalues)

print(C*9/5+32)
print(type(C))

[68.18 68.9  71.42]
<class 'numpy.ndarray'>


In [60]:
sq = np.arange(24)

print(sq)

b = sq.reshape(2,4,3)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [73]:
a = np.arange(24)
b = a.reshape(2,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [28]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [33]:
x = np.ones([3,4])
print(x)

y = np.random.random([5,1,4])
print(y)

c = x+y
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[0.29456814 0.54124837 0.22082627 0.45123997]]

 [[0.90849855 0.04280225 0.55506237 0.34959207]]

 [[0.6119112  0.3852556  0.04404527 0.94327664]]

 [[0.00842925 0.28061969 0.43847974 0.5302618 ]]

 [[0.52282601 0.76539196 0.3639606  0.78005412]]]
[[[1.29456814 1.54124837 1.22082627 1.45123997]
  [1.29456814 1.54124837 1.22082627 1.45123997]
  [1.29456814 1.54124837 1.22082627 1.45123997]]

 [[1.90849855 1.04280225 1.55506237 1.34959207]
  [1.90849855 1.04280225 1.55506237 1.34959207]
  [1.90849855 1.04280225 1.55506237 1.34959207]]

 [[1.6119112  1.3852556  1.04404527 1.94327664]
  [1.6119112  1.3852556  1.04404527 1.94327664]
  [1.6119112  1.3852556  1.04404527 1.94327664]]

 [[1.00842925 1.28061969 1.43847974 1.5302618 ]
  [1.00842925 1.28061969 1.43847974 1.5302618 ]
  [1.00842925 1.28061969 1.43847974 1.5302618 ]]

 [[1.52282601 1.76539196 1.3639606  1.78005412]
  [1.52282601 1.76539196 1.3639606  1.78005412]
  [1.52282601 1.76539196

In [37]:
f = np.array([1,2,4,5],ndmin = 3)
print(f)
print(a.shape)
print(a.ndim)


[[[1 2 4 5]]]
(2, 2)
2


In [39]:
i16 = np.dtype(np.int16)
print(i16)

int16


In [40]:
#create routines 
x = np.empty([3,3],dtype = str)
print(x)

[['' '' '']
 ['' '' '']
 ['' '' '']]


In [50]:
dt = np.dtype([('country','S20'),('density','i4'),('areas','i4'),('population','i4')])
print(type(dt))
print(dt)

<class 'numpy.dtype'>
[('country', 'S20'), ('density', '<i4'), ('areas', '<i4'), ('population', '<i4')]


In [51]:
population_table = np.array([('France',292,122,12299999),('Germany',337,41526,16932222),('Belgium',12,23,444444444)])
print(population_table)

[['France' '292' '122' '12299999']
 ['Germany' '337' '41526' '16932222']
 ['Belgium' '12' '23' '444444444']]


In [52]:
print(population_table[:4])

[['France' '292' '122' '12299999']
 ['Germany' '337' '41526' '16932222']
 ['Belgium' '12' '23' '444444444']]


In [54]:
print(population_table['areas'])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [57]:
dt = np.dtype([('time',[('hr',int),('min',int),('sec',int)]),('temp',float)])

dt
time_temp = np.array([((11,12,13),23.8),((12,1,12),32.1),((12,13,23),21.32)],dtype = dt)

In [58]:
print(time_temp)

[((11, 12, 13), 23.8 ) ((12,  1, 12), 32.1 ) ((12, 13, 23), 21.32)]


In [59]:
print(time_temp['time'])

[(11, 12, 13) (12,  1, 12) (12, 13, 23)]


In [60]:
print(time_temp['temp'])

[23.8  32.1  21.32]


In [62]:
print(time_temp['time']['hr'])

[11 12 12]


# Lamda Function

In [66]:
add = lambda x,y : x+y
add(1,2)

3

In [67]:
g = lambda x: x*x*x
print(g(5))

125


In [68]:
def myfunc(n):
    return lambda a: a*n

mydoubler = myfunc(2)
mytripler = myfunc(3)


print(mydoubler(10))

20


In [69]:
f = lambda x:x>10
print(f(2))

False


In [70]:
li = [1,2,3,4,5,6,7,8]

final_list = list(filter(lambda x: (x%2==0),li))

print(final_list)

[2, 4, 6, 8]


In [71]:
li = [1,2,4,5,56,6,77,7,75,4,4,33]

final_list = list(filter(lambda x:(x%2==1),li))

print(final_list)

[1, 5, 77, 7, 75, 33]


In [72]:
n = [-1,-2,0,1,1,1,2,3]

list(filter(lambda x:x<0,n))

[-1, -2]

In [78]:
dict_a = [{'name':'python','points':10},{'name':'java','points':8}]


print(list(filter(lambda x: x['name']=='java',dict_a)))

[{'name': 'java', 'points': 8}]


# Itertools (Imp.)

In [80]:
import itertools
import functools

lis = [1,2,3,4,5]

In [82]:
print(list(itertools.accumulate(lis,lambda x,y: x+y)))

[1, 3, 6, 10, 15]
